main_project/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.views.static import serve
from html_test.views import R_test
from sra.views import sra
from user_record.views import login, logout

# from editor_md.views import upload_image

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login),
    path('logout/', logout),
    path('R_test/', R_test),
    path('vr_query/', include('vr_query.urls')),
    path('front_press/', include('front_press.urls')),
    path('lizhi_accu_compare/', include('lizhi_accu_compare.urls', namespace='lizhi_accu_compare')),
    path('hx_inner_wiki/', include('hx_inner_wiki.urls')),
    path('editor_md/', include('editor_md.urls')),
    # path('upload/image', upload_image, name='editor_upload_image'),
    path('/static/media/<str:path>', serve, {"document_root": settings.MEDIA_ROOT}),
    path('sra/', sra),  # some static data shows. documents & entrys for frontweb.
    path('CodeTrigger/', include('CodeTrigger.urls')),
    path('autoFront/', include('autoFront.urls')),
    path('Minimum_Test_Set/', include('Minimum_Test_Set.urls')),
    path('OfflineFront/', include('OfflineFront.urls')),
    path('monitor_notice/', include('monitor_notice.urls')),
    path('front_vr_check_unit/', include('front_vr_check_unit.urls')),
]

vr_query/urls.py
from django.urls import path
from .views import mission_list, mission_add, mission_list_page

app_name = 'vr_query'
urlpatterns = [
    path('mission_list/', mission_list),
    path('mission_add/', mission_add),
    path('page/', mission_list_page, name='page')
]

vr_query/models.py
from django.db import models


# Create your models here.
class vr_query_mission(models.Model):
    mission_id = models.AutoField(primary_key=True)
    mission_type = models.CharField(choices=(('query_for_id', 'ID对应查询词'), ('multi_id_query', 'ID交叉查询词')),
                                    default='query_for_id', max_length=20)
    query_from = models.CharField(choices=(('wap', '无线'), ('web', '网页')), max_length=3)
    vrid_list = models.CharField(max_length=107374)
    query_count_is_contained = models.BooleanField(blank=True, default=False)
    query_count = models.IntegerField()
    query_count_for_7 = models.IntegerField()
    order = models.CharField(choices=(('', '无排序'), ('pv', 'pv排序'), ('pvnum', 'pv排序')),
                             default='', max_length=10)
    result_format = models.CharField(max_length=20)
    result_encode = models.CharField(max_length=10)
    user = models.CharField(max_length=50)
    result_url = models.CharField(max_length=200, blank=True)
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(blank=True, null=True)
    mission_status = models.CharField(
        choices=(('Waiting', '等待中'), ('Running', '进行中'), ('Finish', '已结束'), ('Failed', '未成功')), default='Waiting',
        max_length=10)

    class Meta:
        db_table = 'vr_query_mission'

    objects = models.Manager()

vr_query/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from user_record.views import login_checker
from .forms import mission_filter_forms, mission_add_forms
from .models import vr_query_mission
from user_record.models import user_record
import requests
import json


# Create your views here.
@login_checker
def mission_list(request):
    user_info = {}
    uid = request.COOKIES.get("uid")
    if uid:
        user_info = user_record.objects.filter(uid=uid).values('name', 'uno', "uid")[0]
    if request.method == 'POST':
        # 从forms中接收参数
        mission_filter = mission_filter_forms(request.POST)
        if mission_filter.is_valid():
            mission_query_from = mission_filter.cleaned_data['mission_query_from']
            mission_user = mission_filter.cleaned_data['mission_user']
            mission_status = mission_filter.cleaned_data['mission_status']
            mission_list = vr_query_mission.objects.all()
            if mission_query_from:
                mission_list = mission_list.filter(query_from=mission_query_from)
            if mission_user:
                mission_list = mission_list.filter(user=mission_user)
            if mission_status:
                mission_list = mission_list.filter(mission_status=mission_status)
            print(mission_user, mission_status)
        else:
            pass
    elif request.method == 'GET':
        print("[Vr_Query][List]Get list success!")
        mission_filter = mission_filter_forms()
        mission_list = vr_query_mission.objects.all()
        # k = vr_query_mission.objects.filter(mission_id=74)
        # print("GET")
        # for i in k:
        #     # print(dir(i.mission_status))
        #     # print(i.get_mission_status_display())
        #     pass
    return_dict = {'mission_filter': mission_filter,
                   'mission_list': mission_list,
                   'user_info': user_info,
                   }
    return render(request, 'vr_query/mission_list.html', return_dict)


@login_checker
def mission_add(request):
    user_info = {}
    uid = request.COOKIES.get("uid")
    if uid:
        user_info = user_record.objects.filter(uid=uid).values('name', 'uno', "uid")[0]
    if request.method == 'POST':
        mission_config_forms = mission_add_forms(request.POST)
        if mission_config_forms.is_valid():
            mission_type = mission_config_forms.cleaned_data['mission_type']
            vrid_mode = mission_config_forms.cleaned_data['vrid_mode']
            vrid_preserved = mission_config_forms.cleaned_data['vrid_preserved']
            vrid_url = mission_config_forms.cleaned_data['vrid_url']
            vrid_custom = mission_config_forms.cleaned_data['vrid_custom']
            query_from = mission_config_forms.cleaned_data['query_from']
            query_count_is_contained = mission_config_forms.cleaned_data['query_count_is_contained']
            query_count = mission_config_forms.cleaned_data['query_count']
            query_count_for_7 = mission_config_forms.cleaned_data['query_count_for_7']
            query_count_for_multi = mission_config_forms.cleaned_data['query_count_for_multi']
            result_format = mission_config_forms.cleaned_data['result_format']
            result_order = mission_config_forms.cleaned_data['result_order']
            result_encode = mission_config_forms.cleaned_data['result_encode']

            form_errors = []
            vrid_list = []
            vrid_list_type = "0"
            if vrid_mode == '0':
                vrid_preserved_url_list = {
                    '0': 'http://10.153.54.80:81/vrid_preserved/internal.txt',
                    '1': 'http://10.153.54.80:81/vrid_preserved/external.txt',
                    '2': 'http://10.153.54.80:81/vrid_preserved/jiegouhua.txt',
                    '3': 'http://10.153.54.80:81/vrid_preserved/zhilifang.txt',
                    '4': 'http://10.153.54.80:81/vrid_preserved/multihit00.txt',
                    '5': 'http://10.153.54.80:81/vrid_preserved/multihitXX.txt',
                }
                for pre in vrid_preserved:
                    pre_url = vrid_preserved_url_list.get(pre)
                    if pre_url:
                        pre_req = requests.get(url=pre_url)
                        vrid_list += pre_req.text.split('\n')
            elif vrid_mode == '1':
                vrid_req = requests.get(url=vrid_url)
                if vrid_req.status_code == 200:
                    vrid_list_tmp = vrid_req.text.split('\n')
                    if query_count_is_contained:
                        for content in vrid_list_tmp:
                            vrid_list_type = "1"
                            content = content.split('\t')
                            if len(content) == 2:
                                vrid = content[0]
                                count = content[1]
                                vrid_list.append((vrid, count))

                    else:
                        vrid_list = vrid_list_tmp
                    print(vrid_list)
            elif vrid_mode == '2':
                if vrid_custom and len(vrid_custom) >= 8:
                    vrid_list = vrid_custom.split('\r\n')
            if result_format:
                result_format_list = ['query', 'vrid'] + result_format.split(',')
            else:
                result_format_list = ['query', 'vrid']

            if not form_errors:
                new_mission = vr_query_mission.objects.create(
                    mission_type=mission_type,
                    query_from=query_from,
                    vrid_list=vrid_list,
                    query_count_is_contained=query_count_is_contained,
                    query_count=str(query_count),
                    query_count_for_7=str(query_count_for_7),
                    order=result_order,
                    result_format=result_format,
                    result_encode=result_encode,
                    user=user_info['uid'],
                    mission_status='Waiting',
                )
                print(new_mission.mission_id)
                print(new_mission.start_time)

                if mission_type == 'query_for_id':
                    print("[VrQuery]QUERY_FOR_ID")
                    post_dict = {
                        'mission_id': new_mission.mission_id,
                        'query_from': query_from,
                        'vrid_list': vrid_list,
                        'vrid_list_type': vrid_list_type,
                        'query_count': str(query_count),
                        'query_count_for_7': str(query_count_for_7),
                        'order': result_order,
                        'result_format': result_format_list,
                        'result_encode': result_encode,
                        'user': user_info['uid']
                    }
                    post_json = json.dumps(post_dict)
                    post_req = requests.post('http://10.153.54.80:8888/get_query/', data=post_json)
                elif mission_type == 'multi_id_query':
                    print("[VrQuery]MULTI_ID_QUERY")
                    post_dict = {
                        'mission_id': new_mission.mission_id,
                        'query_from': query_from,
                        'vrid_list': vrid_list,
                        'query_count': str(query_count_for_multi),
                        'order': result_order,
                        'result_format': result_format_list,
                        'result_encode': result_encode,
                        'user': user_info['uid']
                    }
                    post_json = json.dumps(post_dict)
                    post_req = requests.post('http://10.153.54.80:8888/multi_id_query/', data=post_json)
                if post_req.status_code == 200:
                    print("[VrQuery]Mission INITIAL OK")
                    return_url = 'http://fs.sogou/vr_query/mission_list'
                else:
                    print("[VrQuery]Mission INITIAL FAILED")
                    new_mission.mission_status = 'Failed'
                return HttpResponseRedirect(return_url)
            # print(vrid_mode)
            # print(vrid_preserved)
            # print(vrid_url)
            # print(vrid_custom)
            # print(query_from)
            # print(query_count)
            # print(query_count_for_7)
            # print(result_format)
            # print(result_order)
            # print(result_encode)
        else:
            print('not PASSED')

    else:
        mission_config_forms = mission_add_forms()
    return_dict = {'mission_config_forms': mission_config_forms,
                   'user_info': user_info,
                   }
    return render(request, 'vr_query/mission_add.html', return_dict)


# 翻页接口
@csrf_exempt
def mission_list_page(request):
    if request.method == 'POST':
        params = json.loads(request.body.decode('utf8'))
        # 基本要素
        draw = params.get('draw')
        start = params.get('start')
        length = params.get('length')
        data_from = int(start)
        data_to = int(start) + int(length)

        mission_list_total = vr_query_mission.objects.all().order_by('-mission_id')
        mission_list_queryset = mission_list_total[data_from:data_to]
        mission_list = []

        if mission_list_queryset:
            for item in mission_list_queryset:
                dict_add = {}
                dict_add.update({
                    'mission_id': item.mission_id,
                    'mission_type': item.get_mission_type_display(),
                    'query_from': item.get_query_from_display(),
                    'user': user_record.objects.filter(uid=item.user).values('name', 'uno', "uid")[0].get('name'),
                    # 'mission_status': item.get_mission_status_display(),
                    'result_url': item.result_url

templates/vr_query/mission_add.html
{% extends 'content.html' %}
{% block head %}
{% include 'head.html' %}
{% endblock head %}
{% block header %}
{% include 'header.html' %}
{% endblock header %}
{% block aside %}
{% include 'aside.html' %}
{% endblock aside %}
{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

{% block custom_head %}
<!--link rel="stylesheet"
    href="http://10.134.104.40/django_statics/AdminLTE/bower_components/select2/dist/css/select2.min.css"-->
{% endblock custom_head %}

{% block custom_script %}
<script>
  function vrid_input() {
    var mode = $('#vrid_mode option:selected').attr('value')
    switch (mode) {
      case '0':
        $('tr#vrid_url').hide()
        $('tr#vrid_custom').hide()
        $('tr#vrid_preserved').show("slow")
        break;
      case '1':
        $('#vrid_preserved').hide()
        $('#vrid_custom').hide()
        $('#vrid_url').show("slow")
        break;
      case '2':
        $('#vrid_preserved').hide()
        $('#vrid_url').hide()
        $('#vrid_custom').show("slow")
        break;
    }
  }

  function order_input() {
    var query_from = $("select[name='query_from'] option:selected").attr('value')
    switch (query_from) {
      case 'web':
        $("select[name='result_order'] option[value='pvnum']" ).remove()
        $("select[name='result_order']").append('<option value="pv">pv排序</option>')
        break;
      case 'wap':
        $("select[name='result_order'] option[value='pv']").remove()
        $("select[name='result_order']").append('<option value="pvnum">pv排序</option>')
        break;
    }
  }

  function mission_type() {
    var type = $('#id_mission_type').find("option:selected").val()
    if (type == "query_for_id") {
      $("[form-type='query_for_id']").parent().parent().show("slow")
      $("[form-type='multi_id_query']").parent().parent().hide()
    } else
    if (type == "multi_id_query") {
      $("[form-type='query_for_id']").parent().parent().hide()
      $("[form-type='multi_id_query']").parent().parent().show("slow")
    }

  }
  $(document).ready(function () {
    vrid_input()
    mission_type()
    $("select[name='result_order']").empty()
    $("select[name='result_order']").append('<option value="" selected>无排序</option>')
    order_input()
    $(function () {
      $('#vrid_mode').change(vrid_input)
      $('#id_mission_type').change(function () {
        mission_type()
        vrid_input()
      })
      $("select[name='query_from']").change(function () {
        order_input()
      })
    })
  })
</script>
{% endblock custom_script %}

<!-- Content Header -->
{% block content_head %}
<section class="content-header">
  <h1>
    欢迎来到质保平台
    <small>welcome</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i>路径1</a></li>
    <li class="active">路径2</li>
  </ol>
</section>
{% endblock content_head %}

<!-- Main content -->
{% block content_body %}
<section class="content container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">增加取词任务</h3>
        </div>
        <form role="form" method='post'>
          {% csrf_token %}
          <div class="row">
            <div class="col-md-12">
              <div class="box-body">
                <div class="row">
                  <div class="col-lg-2 col-md-1 col-sm-0">
                  </div>
                  <div class="col-lg-8 col-md-10 col-sm-12">
                    <div class="col-md-12">
                      <div class="form-group">
                        <table style="width: 100%">
                          <tbody>
                            {% for item in mission_config_forms %}
                            <tr id={{ item.name }}>
                              <td style="width: 40%"><label class="h5">{{ item.label }}{{ item.choices }}</label></td>
                              <td style="width: 50%">{{ item }}</td>
                              <td style="width: 10%">{{ item.errors }}</td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-2 col-md-1 col-sm-0">
                  </div>
                </div>
                <div class="box-footer">
                  <div class="col-md-3 col-md-push-9">
                    <div class="row">
                      <div class="col-md-5">
                        <button type="submit" class="btn btn-primary btn-block">任务开始</button>
                      </div>
                      <div class="col-md-5">
                        <a role="button" class="btn btn-success btn-block" href="/vr_query/mission_list">返回列表</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock content_body %}

templates/vr_query/mission_list.html
{% extends 'content.html' %}
{% block head %}
{% include 'head.html' %}
{% endblock head %}
{% block header %}
{% include 'header.html' %}
{% endblock header %}
{% block aside %}
{% include 'aside.html' %}
{% endblock aside %}
{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

{% block custom_head %}
<!--link rel="stylesheet"
    href="http://10.134.104.40/django_statics/AdminLTE/bower_components/select2/dist/css/select2.min.css"-->
<link rel="stylesheet"
  href="http://10.134.104.40/django_statics/AdminLTE/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
<link rel="stylesheet"
  href="http://10.134.104.40/django_statics/AdminLTE/bower_components/Ionicons/css/ionicons.min.css">
{% endblock custom_head %}

{% block custom_script %}
<script src="http://10.134.104.40/django_statics/AdminLTE/bower_components/datatables.net/js/jquery.dataTables.min.js">
</script>
<script
  src="http://10.134.104.40/django_statics/AdminLTE/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js">
</script>
<script src="http://10.134.104.40/django_statics/AdminLTE/bower_components/jquery-slimscroll/jquery.slimscroll.min.js">
</script>
<script>
  $(document).ready(function () {
    $('#mission_list').DataTable({
      'serverSide': true,
      'paging': true,
      'lengthChange': false,
      'searching': false,
      'ordering': true,
      'info': true,
      'autoWidth': false,
      "language": {
        "sLengthMenu": "每页显示 _MENU_ 项结果",
        "info": "第 _START_ 至 _END_ 项记录，共 _TOTAL_ 项",
        "infoEmpty": "第 0 至 0 项记录，共 0 项",
        "emptyTable": "无可用数据",
        "infoFiltered": "(从_MAX_条记录中过滤)",
        "paginate": {
          "last": "第一页",
          "next": "下一页",
          "previous": "上一页",
          "last": "最后一页",
        }
      },
      'order': [
        [0, "asc"]
      ],
      "bLengthChange": true,
      "pageLength": 10,
      "lengthMenu": [10, 15, 20],
      "ajax": {
        "url": "{% url 'vr_query:page' %}",
        "type": "POST",
        cache: false, //禁用缓存
        data: function (data) {
          return JSON.stringify({
            'draw': data.draw,
            'start': data.start,
            'length': data.length,
          })
        }, //传入已封装的参数
        dataType: "json", //返回数据格式为json
        contentType: "application/json"
        // "data": function ( d ) {
        //     console.log(d)
        // }
      },
      "columns": [{
          "data": "mission_id",
          "width": "5%",
          "defaultContent": "--"
        },
        {
          "data": "mission_type",
          "width": "10%",
          "defaultContent": "--"
        },
        {
          "data": "query_from",
          "width": "7%",
          "defaultContent": "--"
        },
        {
          "data": "user",
          "width": "10%",
          "defaultContent": "--"
        },
        {
          "data": "status",
          "width": "10%",
          "defaultContent": "--"
        },
        {
          "data": "start_time",
          "width": "14%",
          "defaultContent": "--"
        },
        {
          "data": "end_time",
          "width": "14%",
          "defaultContent": "--"
        },
        {
          "data": "result_url",
          "width": "15%",
          "defaultContent": "--"
        },
      ]
    });
  });
</script>
{% endblock custom_script %}

<!-- Content Header -->
{% block content_head %}
<section class="content-header">
  <h1>
    欢迎来到质保平台
    <small>welcome</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i>路径1</a></li>
    <li class="active">路径2</li>
  </ol>
</section>
{% endblock content_head %}

<!-- Main content -->
{% block content_body %}
<section class="content container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">取词任务列表</h3>
        </div>
        <form role="form" method='post'>
          {% csrf_token %}
          <div class="row">
            <div class="col-md-12">
              <div class="box-body">
                <!-- <div class="form-group">
                  <div class="row">
                    <div class="col-md-4">
                      <label class="col-md-3 h5">{{ mission_filter.mission_query_from.label }}</label>
                      {{ mission_filter.mission_query_from }}
                    </div>
                    <div class="col-md-4">
                      <label class="col-md-3 h5">{{ mission_filter.mission_user.label }}</label>
                      {{ mission_filter.mission_user }}
                    </div>
                    <div class="col-md-4">
                      <label class="col-md-3 h5">{{ mission_filter.mission_status.label }}</label>
                      {{ mission_filter.mission_status }}
                    </div>
                  </div>
                </div> -->
                <br>
                <div class="row">
                  <div class="col-md-3 col-md-push-9">
                    <div class="row">
                      <div class="col-md-5">
                        <!-- <button type="submit" class="btn btn-primary btn-block">点击查询</button> -->
                      </div>
                      <div class="col-md-5">
                        <a role="button" class="btn btn-success btn-block" href="/vr_query/mission_add/">添加任务</a>
                      </div>
                    </div>
                  </div>
                </div>
                <br />
                <div class="row">
                  <div class="col-md-12">
                    <table id="mission_list" class="table table-bordered table-striped">
                      <thead>
                        <tr>
                          <th>ID</th>
                          <th>任务种类</th>
                          <th>来源</th>
                          <!-- <th>选取字段</th> -->
                          <th>执行人</th>
                          <th>任务状态</th>
                          <th>开始时间</th>
                          <th>结束时间</th>
                          <th>词表地址</th>
                        </tr>
                      </thead>
                      <!-- <tbody>
                        {% for mission in mission_list %}
                        <tr>
                          <td>{{ mission.mission_id }}</td>
                          <td>{{ mission.get_mission_type_display }}</td>
                          <td>{{ mission.get_query_from_display }}</td>
                          <td>{{ mission.result_format }}</td>
                          <td>{{ mission.user }}</td>
                          <td>{{ mission.get_mission_status_display }}</td>
                          <td>{{ mission.start_time|date:"Y-m-d H:i:s" }}</td>
                          <td>{{ mission.end_time|date:"Y-m-d H:i:s" }}</td>
                          <td><span mission.result_url>{{ mission.result_url }}</span></td>
                        </tr>
                        {% endfor %}
                      </tbody> -->
                    </table>
                  </div>
                </div>
              </div>
              <div class="box-footer">
                <label>分页预留</label>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock content_body %}