front_press/urls.py
from django.urls import path
from .views import mission_list, mission_add

urlpatterns = [
    path('mission_list/', mission_list),
    path('mission_add/', mission_add),
]

main_project/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.views.static import serve
from html_test.views import R_test
from sra.views import sra
from user_record.views import login, logout

# from editor_md.views import upload_image

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login),
    path('logout/', logout),
    path('R_test/', R_test),
    path('vr_query/', include('vr_query.urls')),
    path('front_press/', include('front_press.urls')),
    path('lizhi_accu_compare/', include('lizhi_accu_compare.urls', namespace='lizhi_accu_compare')),
    path('hx_inner_wiki/', include('hx_inner_wiki.urls')),
    path('editor_md/', include('editor_md.urls')),
    # path('upload/image', upload_image, name='editor_upload_image'),
    path('/static/media/<str:path>', serve, {"document_root": settings.MEDIA_ROOT}),
    path('sra/', sra),  # some static data shows. documents & entrys for frontweb.
    path('CodeTrigger/', include('CodeTrigger.urls')),
    path('autoFront/', include('autoFront.urls')),
    path('Minimum_Test_Set/', include('Minimum_Test_Set.urls')),
    path('OfflineFront/', include('OfflineFront.urls')),
    path('monitor_notice/', include('monitor_notice.urls')),
    path('front_vr_check_unit/', include('front_vr_check_unit.urls')),
]

vr_query/urls.py
from django.urls import path
from .views import mission_list, mission_add, mission_list_page

app_name = 'vr_query'
urlpatterns = [
    path('mission_list/', mission_list),
    path('mission_add/', mission_add),
    path('page/', mission_list_page, name='page')
]

front_press/models.py
from django.db import models


# Create your models here.
class FrontPressModel(models.Model):
    id = models.AutoField(primary_key=True)
    author = models.CharField(max_length=20)
    code = models.CharField(max_length=256)
    type = models.CharField(
        max_length=5,
        choices=(
            ('0', 'wap'),
            ('1', 'pc'),
        )
    )
    data_path = models.CharField(max_length=128)
    init_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(blank=True, null=True)
    status = models.CharField(
        max_length=30,
        choices=(
            ('0', '刚提交'),
            ('1', '正在处理'),
            ('2', '处理完成'),
            ('3', '代码无法checkout'),
            ('4', '其他错误')
        )
    )
    result_url = models.CharField(max_length=256)
    result_summary = models.CharField(max_length=1048576)
    comment = models.CharField(max_length=8192)

    class Meta:
        db_table = 'front_press_mission'

front_press/forms.py
from django import forms


class FrontPressForm(forms.Form):
    code = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control col-md-9',
                'style': 'width:70%',
                'rows': '3',
            }),
        label='测试分支地址',
        required=True,
    )

    type = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class': 'form-control col-md-9',
                'style': 'width:70%'
            }),
        label='种类',
        required=True,
        choices=(
            ('0', 'wap'),
            ('1', 'pc'),
        ),
    )

    data_path = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control col-md-9',
                'style': 'width:70%',
                'rows': '3',
            }),
        label='数据文件路径',
        required=True,
    )

vr_query/forms.py
from django import forms


class mission_filter_forms(forms.Form):
    mission_query_from = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class': 'form-control col-md-9',
                'style': 'width:70%',
            }),
        label='取词来源',
        required=False,
        choices=(
            ('', '未选择'),
            ('web', '网页'),
            ('wap', '无线'),
        ),
    )

    mission_user = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control col-md-9',
                'style': 'width:70%',
            }),
        label='执行人员',
        required=False,
    )

    mission_status = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class': 'form-control col-md-9',
                'style': 'width:70%'
            }),
        label='任务状态',
        required=False,
        choices=(
            ('', '未选择'),
            ('Running', '进行中'),
            ('Finish', '已结束'),
            ('Waiting', '等待中'),
            ('Failed', '未成功'),
        ),
    )


class mission_add_forms(forms.Form):
    mission_type = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'form-control',
                                   'style': 'width:60%'}),
        label='任务模式选择',
        required=True,
        choices=(('query_for_id', 'ID对应查询词'),
                 ('multi_id_query', 'ID交叉查询词'),
                 ),
    )
    vrid_mode = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'form-control',
                                   'style': 'width:60%'}),
        label='VRID模式选择',
        required=True,
        choices=(('0', '预设方案'),
                 ('1', '地址读取'),
                 ('2', '网页输入'),
                 ),
    )

    vrid_preserved = forms.MultipleChoiceField(
        widget=forms.SelectMultiple(
            attrs={'class': 'form-control',
                   'size': '6',
                   'style': 'width:60%',
                   'form-type': 'query_for_id multi_id_query', }),
        label='预设分类选择(按住Ctrl键可多选)',
        required=False,
        choices=(('0', '内部VR(1开头)'),
                 ('1', '外部VR(2,4开头)'),
                 ('2', '结构化(3开头)'),
                 ('3', '知立方(5开头)'),
                 ('4', '多命中VR(7开头00)'),
                 ('5', '多命中VR(7开头01-99)'),
                 ),
        error_messages={
            'invalid': '请至少选择一个',
        }
    )

    vrid_url = forms.URLField(
        widget=forms.URLInput(attrs={'class': 'forms-control',
                                     'style': 'width:60%'}),
        label='VRID获取地址(每行一个id)',
        required=False,
        initial="http://target.txt",
        max_length=100,
    )

    vrid_custom = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'forms-control',
                                     'rows': '5',
                                     'placeholder': '每行一个',
                                     'style': 'width:60%', }),
        label='VRID自定义(每行一个id)',
        required=False,
        max_length=32768,
    )

    query_from = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class': 'form-control',
                'style': 'width:60%',
            }),
        label='来源选取',
        required=True,
        choices=(
            ('web', '网页'),
            ('wap', '无线'),
        ),
    )

    query_count_is_contained = forms.BooleanField(
        widget=forms.CheckboxInput(
            attrs={}
        ),
        label='包含取词数',
        required=False,
    )

    query_count = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control',
                                        'style': 'width:60%',
                                        'placeholder': '最大10000',
                                        'form-type': 'query_for_id', }),
        label='取词数(最大10000)',
        required=True,
        initial=10,
        max_value=10000,
        min_value=1,
    )

    query_count_for_7 = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={'class': 'form-control',
                   'style': 'width:60%',
                   'placeholder': '最大5000',
                   'form-type': 'query_for_id', }),
        label='子取词数(最大5000)(对7开头01-99生效)',
        required=True,
        initial=5,
        max_value=5000,
        min_value=1,
    )

    query_count_for_multi = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={'class': 'form-control',
                   'style': 'width:60%',
                   'placeholder': '最大10000',
                   'form-type': 'multi_id_query', }),
        label='取词数(最大10000)',
        required=True,
        initial=10,
        max_value=10000,
        min_value=1,
    )

    result_format = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'forms-control',
                   'placeholder': '默认已带query,vrid',
                   'style': 'width:60%', }),
        label='选取字段',
        required=False,
    )

    result_order = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class': 'form-control',
                'style': 'width:60%',
            }),
        label='排序字段',
        required=False,
        choices=(
            ('', '无排序'),
            ('pv', 'pv排序'),
            ('pvnum', 'pv排序'),
        ),
    )

    result_encode = forms.ChoiceField(
        widget=forms.Select(
            attrs={'class': 'form-control',
                   'style': 'width:60%', }),
        label='结果编码',
        required=True,
        choices=(('utf8', 'utf8'), ('gbk', 'gbk')),
        initial='0',
    )

front_press/views.py
# Create your views here.
from django.http import HttpResponseRedirect
from user_record.views import login_checker
from django.shortcuts import render
from .models import FrontPressModel
from .forms import FrontPressForm
from user_record.models import user_record


# Create your views here.
@login_checker
def mission_list(request):
    user_info = {}
    uid = request.COOKIES.get("uid")
    if uid:
        user_info = user_record.objects.filter(uid=uid).values('name', 'uno', "uid")[0]
    if request.method == 'POST':
        mission_list = FrontPressModel.objects.all()

    elif request.method == 'GET':
        mission_list = FrontPressModel.objects.all()
        print("[Front_Press]ALL:", mission_list)
    return_dict = {
        # 'mission_filter': mission_filter,
        'mission_list': mission_list,
        'user_info': user_info,
    }
    return render(request, 'front_press/mission_list.html', return_dict)


@login_checker
def mission_add(request):
    user_info = {}
    uid = request.COOKIES.get("uid")
    if uid:
        user_info = user_record.objects.filter(uid=uid).values('name', 'uno', "uid")[0]
    if request.method == 'POST':
        front_press_form = FrontPressForm(request.POST)
        if front_press_form.is_valid():
            author = user_info['name']
            code = front_press_form.cleaned_data['code']
            type = front_press_form.cleaned_data['type']
            data_path = front_press_form.cleaned_data['data_path']

            new_mission = FrontPressModel.objects.create(
                author=author,
                code=code,
                type=type,
                data_path=data_path,
                status='0',
            )
            print("[Press_Front]Create Mission")
            return_url = 'http://fs.sogou/front_press/mission_list/'
            return HttpResponseRedirect(return_url)
        else:
            new_mission = FrontPressModel.objects.create(
                author=author,
                code=code,
                type=type,
                data_path=data_path,
                status='4',
            )
            print("[Press_Front]params not valid")
            return_url = 'http://fs.sogou/front_press/mission_list/'
            return HttpResponseRedirect(return_url)

    else:
        front_press_form = FrontPressForm()
    return_dict = {'front_press_form': front_press_form,
                   'user_info': user_info,
                   }
    return render(request, 'front_press/mission_add.html', return_dict)

templates/front_press/mission_add.html
{% extends 'content.html' %}
{% block head %}
{% include 'head.html' %}
{% endblock head %}
{% block header %}
{% include 'header.html' %}
{% endblock header %}
{% block aside %}
{% include 'aside.html' %}
{% endblock aside %}
{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

{% block custom_head %}
<!--link rel="stylesheet"
    href="http://10.134.104.40/django_statics/AdminLTE/bower_components/select2/dist/css/select2.min.css"-->
{% endblock custom_head %}

{% block custom_script %}
<script>
  function vrid_input() {
    var mode = $('#vrid_mode option:selected').attr('value')
    switch (mode) {
      case '0':
        $('tr#vrid_url').hide()
        $('tr#vrid_custom').hide()
        $('tr#vrid_preserved').show("slow")
        break;
      case '1':
        $('#vrid_preserved').hide()
        $('#vrid_custom').hide()
        $('#vrid_url').show("slow")
        break;
      case '2':
        $('#vrid_preserved').hide()
        $('#vrid_url').hide()
        $('#vrid_custom').show("slow")
        break;
    }
  }

  function mission_type() {
    var type = $('#id_mission_type').find("option:selected").val()
    if (type == "query_for_id") {
      $("[form-type='query_for_id']").parent().parent().show("slow")
      $("[form-type='multi_id_query']").parent().parent().hide()
    } else
    if (type == "multi_id_query") {
      $("[form-type='query_for_id']").parent().parent().hide()
      $("[form-type='multi_id_query']").parent().parent().show("slow")
    }

  }
  $(document).ready(function () {
    vrid_input()
    mission_type()
    $(function () {
      $('#vrid_mode').change(vrid_input)
      $('#id_mission_type').change(function () {
        mission_type()
        vrid_input()
      })
    })
  })
</script>
{% endblock custom_script %}

<!-- Content Header -->
{% block content_head %}
<section class="content-header">
  <h1>
    欢迎来到质保平台
    <small>welcome</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i>路径1</a></li>
    <li class="active">路径2</li>
  </ol>
</section>
{% endblock content_head %}

<!-- Main content -->
{% block content_body %}
<section class="content container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">增加任务</h3>
        </div>
        <form role="form" method='post'>
          {% csrf_token %}
          <div class="row">
            <div class="col-md-12">
              <div class="box-body">
                <div class="row">
                  <div class="col-lg-2 col-md-1 col-sm-0">
                  </div>
                  <div class="col-lg-8 col-md-10 col-sm-12">
                    <div class="col-md-12">
                      <div class="form-group">
                        <table style="width: 100%">
                          <tbody>
                            {% for item in front_press_form %}
                            <tr id={{ item.name }}>
                              <td style="width: 40%"><label class="h5">{{ item.label }}{{ item.choices }}</label></td>
                              <td style="width: 50%">{{ item }}</td>
                              <td style="width: 10%">{{ item.errors }}</td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-2 col-md-1 col-sm-0">
                  </div>
                </div>
                <div class="box-footer">
                  <div class="col-md-3 col-md-push-9">
                    <div class="row">
                      <div class="col-md-5">
                        <button type="submit" class="btn btn-primary btn-block">任务开始</button>
                      </div>
                      <div class="col-md-5">
                        <a role="button" class="btn btn-success btn-block" href="/front_press/mission_list/">返回列表</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock content_body %}

templates/front_press/mission_list.html
{% extends 'content.html' %}
{% block head %}
{% include 'head.html' %}
{% endblock head %}
{% block header %}
{% include 'header.html' %}
{% endblock header %}
{% block aside %}
{% include 'aside.html' %}
{% endblock aside %}
{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

{% block custom_head %}
<!--link rel="stylesheet"
    href="http://10.134.104.40/django_statics/AdminLTE/bower_components/select2/dist/css/select2.min.css"-->
<link rel="stylesheet"
  href="http://10.134.104.40/django_statics/AdminLTE/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
<link rel="stylesheet"
  href="http://10.134.104.40/django_statics/AdminLTE/bower_components/Ionicons/css/ionicons.min.css">
{% endblock custom_head %}

{% block custom_script %}
<script src="http://10.134.104.40/django_statics/AdminLTE/bower_components/datatables.net/js/jquery.dataTables.min.js">
</script>
<script
  src="http://10.134.104.40/django_statics/AdminLTE/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js">
</script>
<script src="http://10.134.104.40/django_statics/AdminLTE/bower_components/jquery-slimscroll/jquery.slimscroll.min.js">
</script>
<script>
  $(document).ready(function () {
    $('#mission_list').DataTable({
      'paging': true,
      'lengthChange': false,
      'searching': false,
      'ordering': true,
      'info': true,
      'autoWidth': false,
      "language": {
        "info": "第_PAGE_页(共_PAGES_页)",
        "infoEmpty": "第0页(共0页)",
        "emptyTable": "无可用数据",
        "paginate": {
          "last": "第一页",
          "next": "下一页",
          "previous": "上一页",
          "last": "最后一页",
        }
      },
      'order': [[ 0, "desc" ]]
    });
  });
</script>
{% endblock custom_script %}

<!-- Content Header -->
{% block content_head %}
<section class="content-header">
  <h1>
    欢迎来到质保平台
    <small>welcome</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i>路径1</a></li>
    <li class="active">路径2</li>
  </ol>
</section>
{% endblock content_head %}

<!-- Main content -->
{% block content_body %}
<section class="content container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">前端压力任务历史记录</h3>
        </div>
        <form role="form" method='post'>
          {% csrf_token %}
          <div class="row">
            <div class="col-md-12">
              <div class="box-body">
                <div class="form-group">
                  <div class="row">
                    <div class="col-md-4">
                      <label class="col-md-3 h5">{{ mission_filter.mission_query_from.label }}</label>
                      {{ mission_filter.mission_query_from }}
                    </div>
                    <div class="col-md-4">
                      <label class="col-md-3 h5">{{ mission_filter.mission_user.label }}</label>
                      {{ mission_filter.mission_user }}
                    </div>
                    <div class="col-md-4">
                      <label class="col-md-3 h5">{{ mission_filter.mission_status.label }}</label>
                      {{ mission_filter.mission_status }}
                    </div>
                  </div>
                </div>
                <br>
                <div class="row">
                  <div class="col-md-3 col-md-push-9">
                    <div class="row">
                      <div class="col-md-5">
                        <button type="submit" class="btn btn-primary btn-block">点击查询</button>
                      </div>
                      <div class="col-md-5">
                        <a role="button" class="btn btn-success btn-block" href="/front_press/mission_add/">添加任务</a>
                      </div>
                    </div>
                  </div>
                </div>
                <br />
                <div class="row">
                  <div class="col-md-12">
                    <table id="mission_list" class="table table-bordered table-striped">
                      <thead>
                        <tr>
                          <th>任务ID</th>
                          <th>任务种类</th>
                          <th>执行人</th>
                          <th>代码</th>
                          <th>任务状态</th>
                          <th>开始时间</th>
                          <th>结束时间</th>
                          <th>异常统计</th>
						  <th>结果统计</th>
                        </tr>
                      </thead>
                      <tbody>
                        {% for mission in mission_list %}
                        <tr>
                          <td>{{ mission.id}}</td>
                          <td>{{ mission.get_type_display }}</td>
                          <td>{{ mission.author }}</td>
                          <td>{{ mission.code }}</td>
                          <td>{{ mission.get_status_display }}</td>
                          <td>{{ mission.init_time|date:"Y-m-d H:i:s" }}</td>
                          <td>{{ mission.update_time|date:"Y-m-d H:i:s" }}</td>
                          <td><span mission.result_url>{{ mission.result_url }}</span></td>
						  <td>{{ mission.result_summary }}</td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
              <div class="box-footer">
                <label>分页预留</label>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock content_body %}