lizhi_accu_compare/urls.py
from django.urls import path
from .views import mission_list
from .views import mission_list_case
from .views import unsolved_case
from .views import unsolved_detail
from .views import mission_case_detail

app_name='lizhi_accu_compare'
urlpatterns = [
    path('mission_list/', mission_list, name='mission_list'),
    path('mission_list/unsolved_case/', unsolved_case, name='unsolved_case'),
    # path('unsolved_case/', unsolved_detail, name='unsolved_detail'),
    path('mission_list/<int:task_id>/', mission_list_case, name='case_list'),
    path('mission_list/<int:task_id>/<int:query_id>/', mission_case_detail, name='case_detail')
]

main_project/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.views.static import serve
from html_test.views import R_test
from sra.views import sra
from user_record.views import login, logout

# from editor_md.views import upload_image

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', login),
    path('logout/', logout),
    path('R_test/', R_test),
    path('vr_query/', include('vr_query.urls')),
    path('front_press/', include('front_press.urls')),
    path('lizhi_accu_compare/', include('lizhi_accu_compare.urls', namespace='lizhi_accu_compare')),
    path('hx_inner_wiki/', include('hx_inner_wiki.urls')),
    path('editor_md/', include('editor_md.urls')),
    # path('upload/image', upload_image, name='editor_upload_image'),
    path('/static/media/<str:path>', serve, {"document_root": settings.MEDIA_ROOT}),
    path('sra/', sra),  # some static data shows. documents & entrys for frontweb.
    path('CodeTrigger/', include('CodeTrigger.urls')),
    path('autoFront/', include('autoFront.urls')),
    path('Minimum_Test_Set/', include('Minimum_Test_Set.urls')),
    path('OfflineFront/', include('OfflineFront.urls')),
    path('monitor_notice/', include('monitor_notice.urls')),
    path('front_vr_check_unit/', include('front_vr_check_unit.urls')),
]

vr_query/urls.py
from django.urls import path
from .views import mission_list, mission_add, mission_list_page

app_name = 'vr_query'
urlpatterns = [
    path('mission_list/', mission_list),
    path('mission_add/', mission_add),
    path('page/', mission_list_page, name='page')
]

lizhi_accu_compare/models.py
from django.db import models


# Create your models here.
class LizhiAccuMission(models.Model):
    task_id = models.AutoField(primary_key=True)
    start_time = models.DateTimeField(auto_now_add=True)
    end_time = models.DateTimeField(blank=True, null=True)
    status = models.CharField(
        max_length=30,
        choices=(
            ('0', '未开始'),
            ('1', '进行中'),
            ('2', '已完成'),
        )
    )

    class Meta:
        db_table = 'lizhi_accu_mission'


class LizhiAccuResult(models.Model):
    query_id = models.AutoField(primary_key=True)
    task_id = models.ForeignKey(LizhiAccuMission, on_delete=models.DO_NOTHING)
    query = models.CharField(max_length=1024)
    sogou_res = models.CharField(max_length=107374)
    baidu_res = models.CharField(max_length=107374)
    sogou_pic = models.CharField(max_length=107374)
    baidu_pic = models.CharField(max_length=107374)
    precision = models.CharField(
        max_length=30,
        choices=(
            ('0', '未处理'),
            ('1', '错误'),
            ('2', '需要改进'),
            ('3', '效果正常'),
        )
    )
    status = models.CharField(
        max_length=30,
        choices=(
            ('0', '未解决'),
            ('1', '已解决'),
            ('2', '无问题'),
        )
    )
    solve_time = models.DateField(blank=True, null=True)
    comments = models.CharField(max_length=107374, blank=True, null=True, default='')
    edit_member = models.CharField(max_length=20, blank=True, null=True, default='')
    lizhi_type = models.CharField(
        max_length=30,
        default='0',
        choices=(
            ('0', '未标记'),
            ('1', '图谱'),
            ('2', 'VR'),
            ('3', '立知短答案'),
            ('4', '立知长答案'),
            ('5', '优质问答'),
        )
    )
    focus_member = models.CharField(max_length=100, blank=True, null=True, default='')
    edit_time = models.DateTimeField(blank=True, null=True)
    itest_record_title = models.CharField(max_length=100, blank=True, null=True, default='NULL')
    itest_record_id = models.CharField(max_length=20, blank=True, null=True, default='')


    class Meta:
        db_table = 'lizhi_accu_result'

lizhi_accu_compare/forms.py
from django import forms
from .models import LizhiAccuResult


class ListFilter(forms.Form):
    lizhi_type = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class': 'form-control',
                'style': 'width:60%',
            }),
        label='立知分类',
        required=True,
        choices=(
            ('99', '全部'),
            ('0', '未标记'),
            ('1', '图谱'),
            ('2', 'VR'),
            ('3', '立知短答案'),
            ('4', '立知长答案'),
            ('5', '优质问答'),
        ),
        # default='0',
    )

    focus_member = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'forms-control',
                'style': 'width:60%',
            }),
        label='关注人',
        required=False,
    )


class CaseDetailStatus(forms.ModelForm):
    status = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class': 'form-control',
                'style': 'width:100%',
            }),
        label='处理状态',
        required=True,
        choices=(
            ('0', '未解决'),
            ('1', '已解决'),
            ('2', '无问题'),
        )
    )

    precision = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class': 'form-control',
                'style': 'width:100%',
            }),
        label='判定结果',
        required=True,
        choices=(
            ('0', '未处理'),
            ('1', '错误'),
            ('2', '需要改进'),
            ('3', '效果正常'),
        ),
    )

    solve_time = forms.DateField(
        widget=forms.DateInput(
            attrs={
                'class': 'form-control',
                'style': 'width:100%',
            }
        ),
        label='预计解决时间',
        required=False,
        initial=''
    )

    comments = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'forms-control',
                                     'rows': '2',
                                     # 'placeholder': '每行一个',
                                     'style': 'width:100%', }),
        label='备注',
        max_length=107374,
        required=False,
    )

    lizhi_type = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class': 'form-control',
                'style': 'width:100%',
            }),
        label='立知分类',
        required=True,
        choices=(
            ('0', '未标记'),
            ('1', '图谱'),
            ('2', 'VR'),
            ('3', '立知短答案'),
            ('4', '立知长答案'),
            ('5', '优质问答'),
        ),
        # default='0',
    )

    focus_member = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'forms-control',
                'style': 'width:100%',
            }),
        label='关注人',
        required=False,
    )

    itest_record_title = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'class': 'forms-control',
                'style': 'width:100%',
            }),
        label='问题记录标题',
    )

    # is_next = forms.ChoiceField(
    #     widget=forms.CheckboxInput(
    #         attrs={
    #             'style': 'display:none',
    #         }
    #     ),
    #     choices=(
    #         (True, True),
    #         (False, False),
    #     ),
    #     required=False,
    # )

    class Meta:
        model = LizhiAccuResult
        fields = [
            'status', 'precision', 'solve_time',
            'comments', 'lizhi_type', 'focus_member',
            'itest_record_title',
        ]

vr_query/forms.py
from django import forms


class mission_filter_forms(forms.Form):
    mission_query_from = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class': 'form-control col-md-9',
                'style': 'width:70%',
            }),
        label='取词来源',
        required=False,
        choices=(
            ('', '未选择'),
            ('web', '网页'),
            ('wap', '无线'),
        ),
    )

    mission_user = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control col-md-9',
                'style': 'width:70%',
            }),
        label='执行人员',
        required=False,
    )

    mission_status = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class': 'form-control col-md-9',
                'style': 'width:70%'
            }),
        label='任务状态',
        required=False,
        choices=(
            ('', '未选择'),
            ('Running', '进行中'),
            ('Finish', '已结束'),
            ('Waiting', '等待中'),
            ('Failed', '未成功'),
        ),
    )


class mission_add_forms(forms.Form):
    mission_type = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'form-control',
                                   'style': 'width:60%'}),
        label='任务模式选择',
        required=True,
        choices=(('query_for_id', 'ID对应查询词'),
                 ('multi_id_query', 'ID交叉查询词'),
                 ),
    )
    vrid_mode = forms.ChoiceField(
        widget=forms.Select(attrs={'class': 'form-control',
                                   'style': 'width:60%'}),
        label='VRID模式选择',
        required=True,
        choices=(('0', '预设方案'),
                 ('1', '地址读取'),
                 ('2', '网页输入'),
                 ),
    )

    vrid_preserved = forms.MultipleChoiceField(
        widget=forms.SelectMultiple(
            attrs={'class': 'form-control',
                   'size': '6',
                   'style': 'width:60%',
                   'form-type': 'query_for_id multi_id_query', }),
        label='预设分类选择(按住Ctrl键可多选)',
        required=False,
        choices=(('0', '内部VR(1开头)'),
                 ('1', '外部VR(2,4开头)'),
                 ('2', '结构化(3开头)'),
                 ('3', '知立方(5开头)'),
                 ('4', '多命中VR(7开头00)'),
                 ('5', '多命中VR(7开头01-99)'),
                 ),
        error_messages={
            'invalid': '请至少选择一个',
        }
    )

    vrid_url = forms.URLField(
        widget=forms.URLInput(attrs={'class': 'forms-control',
                                     'style': 'width:60%'}),
        label='VRID获取地址(每行一个id)',
        required=False,
        initial="http://target.txt",
        max_length=100,
    )

    vrid_custom = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'forms-control',
                                     'rows': '5',
                                     'placeholder': '每行一个',
                                     'style': 'width:60%', }),
        label='VRID自定义(每行一个id)',
        required=False,
        max_length=32768,
    )

    query_from = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class': 'form-control',
                'style': 'width:60%',
            }),
        label='来源选取',
        required=True,
        choices=(
            ('web', '网页'),
            ('wap', '无线'),
        ),
    )

    query_count_is_contained = forms.BooleanField(
        widget=forms.CheckboxInput(
            attrs={}
        ),
        label='包含取词数',
        required=False,
    )

    query_count = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control',
                                        'style': 'width:60%',
                                        'placeholder': '最大10000',
                                        'form-type': 'query_for_id', }),
        label='取词数(最大10000)',
        required=True,
        initial=10,
        max_value=10000,
        min_value=1,
    )

    query_count_for_7 = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={'class': 'form-control',
                   'style': 'width:60%',
                   'placeholder': '最大5000',
                   'form-type': 'query_for_id', }),
        label='子取词数(最大5000)(对7开头01-99生效)',
        required=True,
        initial=5,
        max_value=5000,
        min_value=1,
    )

    query_count_for_multi = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={'class': 'form-control',
                   'style': 'width:60%',
                   'placeholder': '最大10000',
                   'form-type': 'multi_id_query', }),
        label='取词数(最大10000)',
        required=True,
        initial=10,
        max_value=10000,
        min_value=1,
    )

    result_format = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'forms-control',
                   'placeholder': '默认已带query,vrid',
                   'style': 'width:60%', }),
        label='选取字段',
        required=False,
    )

    result_order = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class': 'form-control',
                'style': 'width:60%',
            }),
        label='排序字段',
        required=False,
        choices=(
            ('', '无排序'),
            ('pv', 'pv排序'),
            ('pvnum', 'pv排序'),
        ),
    )

    result_encode = forms.ChoiceField(
        widget=forms.Select(
            attrs={'class': 'form-control',
                   'style': 'width:60%', }),
        label='结果编码',
        required=True,
        choices=(('utf8', 'utf8'), ('gbk', 'gbk')),
        initial='0',
    )

templates/lizhi_accu_compare/mission_add.html
{% extends 'content.html' %}
{% block head %}
{% include 'head.html' %}
{% endblock head %}
{% block header %}
{% include 'header.html' %}
{% endblock header %}
{% block aside %}
{% include 'aside.html' %}
{% endblock aside %}
{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

{% block custom_head %}
<!--link rel="stylesheet"
    href="http://10.134.104.40/django_statics/AdminLTE/bower_components/select2/dist/css/select2.min.css"-->
{% endblock custom_head %}

{% block custom_script %}
<script>
  function vrid_input() {
    var mode = $('#vrid_mode option:selected').attr('value')
    switch (mode) {
      case '0':
        $('tr#vrid_url').hide()
        $('tr#vrid_custom').hide()
        $('tr#vrid_preserved').show("slow")
        break;
      case '1':
        $('#vrid_preserved').hide()
        $('#vrid_custom').hide()
        $('#vrid_url').show("slow")
        break;
      case '2':
        $('#vrid_preserved').hide()
        $('#vrid_url').hide()
        $('#vrid_custom').show("slow")
        break;
    }
  }

  function mission_type() {
    var type = $('#id_mission_type').find("option:selected").val()
    if (type == "query_for_id") {
      $("[form-type='query_for_id']").parent().parent().show("slow")
      $("[form-type='multi_id_query']").parent().parent().hide()
    } else
    if (type == "multi_id_query") {
      $("[form-type='query_for_id']").parent().parent().hide()
      $("[form-type='multi_id_query']").parent().parent().show("slow")
    }

  }
  $(document).ready(function () {
    vrid_input()
    mission_type()
    $(function () {
      $('#vrid_mode').change(vrid_input)
      $('#id_mission_type').change(function () {
        mission_type()
        vrid_input()
      })
    })
  })
</script>
{% endblock custom_script %}

<!-- Content Header -->
{% block content_head %}
<section class="content-header">
  <h1>
    欢迎来到质保平台
    <small>welcome</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i>路径1</a></li>
    <li class="active">路径2</li>
  </ol>
</section>
{% endblock content_head %}

<!-- Main content -->
{% block content_body %}
<section class="content container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">增加取词任务</h3>
        </div>
        <form role="form" method='post'>
          {% csrf_token %}
          <div class="row">
            <div class="col-md-12">
              <div class="box-body">
                <div class="row">
                  <div class="col-lg-2 col-md-1 col-sm-0">
                  </div>
                  <div class="col-lg-8 col-md-10 col-sm-12">
                    <div class="col-md-12">
                      <div class="form-group">
                        <table style="width: 100%">
                          <tbody>
                            {% for item in mission_config_forms %}
                            <tr id={{ item.name }}>
                              <td style="width: 40%"><label class="h5">{{ item.label }}{{ item.choices }}</label></td>
                              <td style="width: 50%">{{ item }}</td>
                              <td style="width: 10%">{{ item.errors }}</td>
                            </tr>
                            {% endfor %}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                  <div class="col-lg-2 col-md-1 col-sm-0">
                  </div>
                </div>
                <div class="box-footer">
                  <div class="col-md-3 col-md-push-9">
                    <div class="row">
                      <div class="col-md-5">
                        <button type="submit" class="btn btn-primary btn-block">任务开始</button>
                      </div>
                      <div class="col-md-5">
                        <a role="button" class="btn btn-success btn-block" href="/vr_query/mission_list">返回列表</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock content_body %}

templates/lizhi_accu_compare/mission_case_detail.html
{% extends 'content.html' %}
{% block head %}
{% include 'head.html' %}
{% endblock head %}
{% block header %}
{% include 'header.html' %}
{% endblock header %}
{% block aside %}
{% include 'aside.html' %}
{% endblock aside %}
{% block footer %}
{% include 'footer.html' %}
{% endblock footer %}

{% block custom_head %}
<!--link rel="stylesheet"
    href="http://10.134.104.40/django_statics/AdminLTE/bower_components/select2/dist/css/select2.min.css"-->
<link rel="stylesheet"
    href="http://10.134.104.40/django_statics/AdminLTE/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
<link rel="stylesheet"
    href="http://10.134.104.40/django_statics/AdminLTE/bower_components/Ionicons/css/ionicons.min.css">
<link rel="stylesheet"
    href="http://10.134.104.40/django_statics/AdminLTE/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css">
{% endblock custom_head %}

{% block custom_script %}
<script src="http://10.134.104.40/django_statics/AdminLTE/bower_components/datatables.net/js/jquery.dataTables.min.js">
</script>
<script
    src="http://10.134.104.40/django_statics/AdminLTE/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js">
</script>
<script src="http://10.134.104.40/django_statics/AdminLTE/bower_components/jquery-slimscroll/jquery.slimscroll.min.js">
</script>
<!-- bootstrap datepicker -->
<script
    src="http://10.134.104.40/django_statics/AdminLTE/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js">
</script>
<script
    src="http://10.134.104.40/django_statics/AdminLTE/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.zh-CN.js">
</script>

<script>
    function sleep(n) { //n表示的毫秒数
        var start = new Date().getTime();
        while (true)
            if (new Date().getTime() - start > n) break;
    }

    function auto_href() {
        sleep(2000);
        window.location.href =
            "{% url 'lizhi_accu_compare:case_detail' case_detail.task_id.task_id case_detail.query_id|add:1  %}";
    }

    function submit_next() {
        // $("#id_is_next").attr("checked", true)
        $("form").submit(function () {
            return false;
        });
        setTimeout(function () {
            test();
        }, 2000);
        window.location.href =
            "{% url 'lizhi_accu_compare:case_detail' case_detail.task_id.task_id case_detail.query_id|add:1  %}";
        // return false;
    }

    function precision_input() {
        var mode = $('#id_precision option:selected').attr('value')
        // alert(mode)
        switch (mode) {
            case '3':
                $('#id_status').val('2')
                break;
        }
    }

    $(document).ready(function () {
        $('#id_precision').change(
            function () {
                precision_input()
            }
        )
        $('#id_solve_time').datepicker({
            language: 'zh-CN',
            format: 'yyyy-mm-dd',
            autoclose: true,
            todayHighlight: true,
        }) 
        {% if save_success == "success" %}
        auto_href() 
        {% endif %}
    })
</script>
{% endblock custom_script %}

<!-- Content Header -->
{% block content_head %}
<section class="content-header">
    <h1>
        欢迎来到质保平台
        <small>welcome</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="{% url 'lizhi_accu_compare:mission_list' %}"><i class="fa fa-dashboard"></i>立知精准对比</a>
        </li>
        <li class="active">
            <a href="{% url 'lizhi_accu_compare:case_list' case_detail.task_id.task_id %}"><i
                    class="fa fa-dashboard"></i>现场列表</a>
        </li>
    </ol>
</section>
{% endblock content_head %}

<!-- Main content -->
{% block content_body %}
<section class="content container-fluid">
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">查询词现场</h3>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="box-body">
                            <div class="row">
                                {% if save_success == "success" %}
                                <div class="callout callout-success">
                                    <h4>修改成功！</h4>
                                    <p>1.5秒后跳转到下一Case</p>
                                </div>
                                {% elif save_success == "success_last" %}
                                <div class="callout callout-success">
                                    <h4>修改成功！</h4>
                                    <p>已经到最后一个Case</p>
                                </div>
                                {% endif %}
                                <div class="col-md-12">
                                    <p>查询词:{{ case_detail.query }}</p>
                                    {% if case_detail.itest_record_id %}
                                    <p>此问题已汇总到<a target="_blank" href="http://itest.sogou-inc.com/#!/bugShow/{{ case_detail.itest_record_id }}/">http://itest.sogou-inc.com/#!/bugShow/{{ case_detail.itest_record_id }}/</a></p>
                                    {% endif %}
                                </div>
                                <form role="form" method='post'>
                                    {% csrf_token %}
                                    <div class="col-md-12">
                                        <table class="table-bordered">
                                            <thead>
                                                <tr>
                                                    <th style="width:10%;font-size: 16px">项目</th>
                                                    <th style="width:44%;font-size: 16px">搜狗结果</th>
                                                    <th style="width:2%"></th>
                                                    <th style="width:44%;font-size: 16px">百度结果</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>现场样式</td>
                                                    <td>
                                                        <img class="img-responsive" src="{{ case_detail.sogou_pic }}"
                                                            alt="Photo">
                                                    </td>
                                                    <td></td>
                                                    <td>
                                                        <img class="img-responsive" src="{{ case_detail.baidu_pic }}"
                                                            alt="Photo">
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>文字结果</td>
                                                    <td>{{ case_detail.sogou_res }}</td>
                                                    <td></td>
                                                    <td>{{ case_detail.baidu_res }}</td>
                                                </tr>

                                            </tbody>
                                        </table>
                                    </div>

                            </div>
                        </div>
                        <!-- <div class="box-footer">
                <label>分页预留</label>
              </div> -->
                    </div>
                </div>
                </form>
                <div class="box box-primary">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="box-body">
                                <form role="form" method='post'>
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-md-1">
                                            <label>{{ case_detail_status.precision.label }}</label>
                                        </div>
                                        <div class="col-md-2">
                                            {{ case_detail_status.precision }}
                                        </div>
                                        <div class="col-md-1">
                                            <label>{{ case_detail_status.status.label }}</label>
                                        </div>
                                        <div class="col-md-2">
                                            {{ case_detail_status.status }}
                                        </div>
                                        <div class="col-md-1">
                                            {{ case_detail_status.solve_time.label }}
                                        </div>
                                        <div class="col-md-2">
                                            {{ case_detail_status.solve_time }}
                                        </div>
                                        <div class="col-md-1">
                                            <label>{{ case_detail_status.comments.label }}</label>
                                        </div>
                                        <div class="col-md-2">
                                            {{ case_detail_status.comments }}
                                            {{ case_detail_status.is_next }}
                                            <!-- {{ case_detail_status.is_next.error }} -->
                                        </div>
                                        <div class="col-md-1">
                                            <label>{{ case_detail_status.lizhi_type.label }}</label>
                                        </div>
                                        <div class="col-md-2">
                                            {{ case_detail_status.lizhi_type }}
                                        </div>
                                        <div class="col-md-1">
                                            <label>{{ case_detail_status.focus_member.label }}</label>
                                        </div>
                                        <div class="col-md-2">
                                            {{ case_detail_status.focus_member }}
                                        </div>
                                        <div class="col-md-1">
                                            <label>{{ case_detail_status.itest_record_title.label }}</label>
                                        </div>
                                        <div class="col-md-2">
                                            {{ case_detail_status.itest_record_title }}
                                        </div>
                                        <div class="col-md-12 col-md-offset-7">
                                            <button type="submit" class="btn btn-primary">提交修改</button>
                                            <a role="button" class="btn btn-success"
                                                href="{% url 'lizhi_accu_compare:case_list' case_detail.task_id.task_id %}">返回此任务列表</a>
                                                <a role="button" class="btn btn-warning"
                                                href="{% url 'lizhi_accu_compare:unsolved_case' %}">返回未解决列表</a>
                                            {% if prev_disable %}
                                            <a role="button" class="btn btn-default" %} {{ prev_disable }}>上一个</a>
                                            {% else %}
                                            <a role="button" class="btn btn-default"
                                                href="{% url 'lizhi_accu_compare:case_detail' case_detail.task_id.task_id case_detail.query_id|add:-1 %}"
                                                {{ prev_disable}}>上一个</a>
                                            {% endif %}
                                            {% if next_disable %}
                                            <a role="button" class="btn btn-default" {{ next_disable }}>下一个</a>
                                            {% else %}
                                            <a role="button" class="btn btn-default"
                                                href="{% url 'lizhi_accu_compare:case_detail' case_detail.task_id.task_id case_detail.query_id|add:1  %}"
                                                {{ next_disable }}>下一个</a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content_body %}